services:
  - type: web
    name: aftercallpro
    env: python
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health

    buildCommand: "bash render-build.sh"
    startCommand: "gunicorn -w 2 -k gthread --threads 8 -b 0.0.0.0:$PORT app:app"

    envVars:
      - key: PYTHON_VERSION
        value: "3.13.4"
